import { Product, PriceHistory, ActivityLog, UserProfile } from "../types";

export const INITIAL_USERS: UserProfile[] = [
  {
    id: "user_ramesh",
    name: "Ramesh",
    role: "Admin",
    shortName: "Ramesh",
    color: "#2563EB",
  },
  {
    id: "user_suresh",
    name: "Suresh",
    role: "Manager",
    shortName: "Suresh",
    color: "#7C3AED",
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    name: "Amul Butter",
    category: "Dairy & Eggs",
    brand: "Amul",
    unit: "500g",
    purchase_price: 255,
    selling_price: 275,
    variants: [
      { id: "v1_1", unit: "100g", selling_price: 58 },
      { id: "v1_2", unit: "500g", selling_price: 275 },
      { id: "v1_3", unit: "1kg", selling_price: 530 },
      { id: "v1_5", unit: "5kg", selling_price: 1530 },
      { id: "v1_4", unit: "10kg", selling_price: 2030 },
    ],
    current_stock: 18,
    min_stock: 5,
    barcode: "8901262010152",
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_2",
    name: "Amul Taaza Toned Milk",
    category: "Dairy & Eggs",
    brand: "Amul",
    unit: "1L",
    purchase_price: 52,
    selling_price: 56,
    variants: [
      { id: "v2_1", unit: "500ml", selling_price: 29 },
      { id: "v2_2", unit: "1L", selling_price: 56 },
    ],
    current_stock: 30,
    min_stock: 10,
    barcode: "8901262020021",
    updated_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_by: "Suresh",
  },
  {
    id: "prod_3",
    name: "Tata Salt Vacuum Evaporated",
    category: "Spices & Seasoning",
    brand: "Tata",
    unit: "1kg",
    purchase_price: 24,
    selling_price: 28,
    variants: [
      { id: "v3_1", unit: "1kg", selling_price: 28 },
      { id: "v3_2", unit: "2kg", selling_price: 54 },
    ],
    current_stock: 45,
    min_stock: 10,
    barcode: "8901030381024",
    updated_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_4",
    name: "Aashirvaad Shudh Chakki Atta",
    category: "Atta & Flours",
    brand: "Aashirvaad",
    unit: "10kg",
    purchase_price: 410,
    selling_price: 445,
    variants: [
      { id: "v4_1", unit: "5kg", selling_price: 235 },
      { id: "v4_2", unit: "10kg", selling_price: 445 },
    ],
    current_stock: 12,
    min_stock: 4,
    barcode: "8901725131012",
    updated_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_5",
    name: "Fortune Sunlite Refined Sunflower Oil",
    category: "Edible Oils & Ghee",
    brand: "Fortune",
    unit: "1L Pouch",
    purchase_price: 128,
    selling_price: 142,
    current_stock: 24,
    min_stock: 6,
    barcode: "8906007280015",
    updated_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_by: "Suresh",
  },
  {
    id: "prod_6",
    name: "Tata Sampann Unpolished Toor Dal",
    category: "Dal & Pulses",
    brand: "Tata Sampann",
    unit: "1kg",
    purchase_price: 162,
    selling_price: 178,
    current_stock: 14,
    min_stock: 5,
    barcode: "8901030582032",
    updated_at: new Date(Date.now() - 3600000 * 30).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_7",
    name: "Madhur Pure & Hygienic Sugar",
    category: "Sugar & Sweeteners",
    brand: "Madhur",
    unit: "5kg",
    purchase_price: 210,
    selling_price: 230,
    current_stock: 15,
    min_stock: 5,
    barcode: "8906005230114",
    updated_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    updated_by: "Suresh",
  },
  {
    id: "prod_8",
    name: "Everest Turmeric Powder (Haldi)",
    category: "Spices & Seasoning",
    brand: "Everest",
    unit: "200g",
    purchase_price: 58,
    selling_price: 68,
    current_stock: 25,
    min_stock: 8,
    barcode: "8901786010014",
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_by: "Suresh",
  },
  {
    id: "prod_9",
    name: "Maggi 2-Minute Masala Noodles Pack",
    category: "Snacks & Instant Food",
    brand: "Nestle",
    unit: "70g x 4",
    purchase_price: 52,
    selling_price: 58,
    current_stock: 35,
    min_stock: 10,
    barcode: "8901058852384",
    updated_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_10",
    name: "Parle-G Gold Biscuits",
    category: "Biscuits & Cookies",
    brand: "Parle",
    unit: "1kg Bag",
    purchase_price: 115,
    selling_price: 130,
    current_stock: 18,
    min_stock: 5,
    barcode: "8901719114007",
    updated_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    updated_by: "Suresh",
  },
  {
    id: "prod_11",
    name: "Surf Excel Quick Wash Powder",
    category: "Cleaning & Household",
    brand: "Surf Excel",
    unit: "1kg",
    purchase_price: 135,
    selling_price: 148,
    current_stock: 16,
    min_stock: 5,
    barcode: "8901030704403",
    updated_at: new Date(Date.now() - 3600000 * 36).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_12",
    name: "Dettol Original Bathing Soap",
    category: "Personal Care",
    brand: "Dettol",
    unit: "125g x 3",
    purchase_price: 132,
    selling_price: 145,
    current_stock: 3, // LOW STOCK ALERT DEMO!
    min_stock: 6,
    barcode: "8901396388019",
    updated_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    updated_by: "Suresh",
  },
  {
    id: "prod_13",
    name: "Brooke Bond Red Label Tea",
    category: "Beverages & Tea",
    brand: "Brooke Bond",
    unit: "500g",
    purchase_price: 240,
    selling_price: 265,
    current_stock: 10,
    min_stock: 4,
    barcode: "8901030022033",
    updated_at: new Date(Date.now() - 3600000 * 15).toISOString(),
    updated_by: "Ramesh",
  },
  {
    id: "prod_14",
    name: "MDH Deggi Mirch Powder",
    category: "Spices & Seasoning",
    brand: "MDH",
    unit: "100g",
    purchase_price: 78,
    selling_price: 88,
    current_stock: 2, // LOW STOCK ALERT DEMO!
    min_stock: 5,
    barcode: "8901237010040",
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    updated_by: "Suresh",
  },
];

export const INITIAL_PRICE_HISTORY: PriceHistory[] = [
  {
    id: "hist_1",
    product_id: "prod_3",
    product_name: "Tata Salt Vacuum Evaporated",
    old_price: 26,
    new_price: 28,
    changed_by: "Ramesh",
    reason: "Distributor price revision",
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: "hist_2",
    product_id: "prod_1",
    product_name: "Amul Butter",
    old_price: 265,
    new_price: 275,
    changed_by: "Ramesh",
    reason: "Dairy cost increase",
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "hist_3",
    product_id: "prod_8",
    product_name: "Everest Turmeric Powder (Haldi)",
    old_price: 65,
    new_price: 68,
    changed_by: "Suresh",
    reason: "Wholesale mandi rate adjustment",
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "hist_4",
    product_id: "prod_2",
    product_name: "Amul Taaza Toned Milk",
    old_price: 54,
    new_price: 56,
    changed_by: "Suresh",
    reason: "Official Amul MRP hike",
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "act_1",
    action_type: "PRICE_CHANGE",
    title: "Tata Salt price updated",
    description: "Changed from ₹26 to ₹28 (+₹2)",
    user_name: "Ramesh",
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: "act_2",
    action_type: "PRICE_CHANGE",
    title: "Amul Butter price updated",
    description: "Changed from ₹265 to ₹275 (+₹10)",
    user_name: "Ramesh",
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "act_3",
    action_type: "STOCK_UPDATE",
    title: "Amul Milk stock received",
    description: "Added 20 units (Total: 30L)",
    user_name: "Suresh",
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: "act_4",
    action_type: "PRICE_CHANGE",
    title: "Everest Haldi price updated",
    description: "Changed from ₹65 to ₹68 (+₹3)",
    user_name: "Suresh",
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "act_5",
    action_type: "SYSTEM",
    title: "Store Sync Active",
    description: "KiranaSync initialized with 14 products",
    user_name: "System",
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];
